server:
  port:8080

spring:
  # DB 설정
  datasource:
    # 외부망

    # 내부망
    url: ENC(*)
    username: *
    password: *

logging:
  level:
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    #    org.springframework.web.client.RestTemplate: TRACE
    ai.maum.mcl.skins.api: DEBUG

service:
  server:
    url: url
  cors:
    # 요청 허용 대상 목록
    origins: ${service.server.url}, http://localhost:3000, https://localhost:3000, url1, url2, url3, url4, url5, url6, null
    # 허용 헤더 목록
    headers: Content-Type
    # 자격증명 설정
    credentials: true
    # method
    methods: GET, POST, PUT, DELETE, OPTIONS, TRACE

temp:
  key1: test
